### ISSUE TITLE
Cursor not aligned properly

### ISSUE THREAD

**Issue by ahmadsohail404** [ahmadsohail404/Netflix-UI-Clone#1]
<img width="1058" alt="Screenshot 2021-10-03 at 1 08 25 AM" src="https://user-images.githubusercontent.com/72069769/135729787-56976128-66a4-4435-8cb0-7b291a7f53e0.png">

**Comment by Prasang023** [comment]
Can i work on this?

**Comment by SoundaryaKhanapur** [comment]
May I work on this?

**Comment by Amritanshu02** [comment]
Hello, I would like to work on this issue, could you please assign it to me
