### ISSUE TITLE
Change FAQ section  appearence using css and js

### ISSUE THREAD

**Issue by Muskan-creator** [ahmadsohail404/Netflix-UI-Clone#12]
Please Assign me this issue @ahmadsohail404 as a part of hacktoberfest

**Comment by ahmadsohail404** [comment]
Go ahead!

**Comment by Muskan-creator** [comment]
I have opened a pull request .if all looks good please merge it @ahmadsohail404

**Comment by ahmadsohail404** [comment]
host and and put the link here
