### ISSUE TITLE
Fix page responsiveness

### ISSUE THREAD

**Issue by ahmadsohail404** [ahmadsohail404/Netflix-UI-Clone#2]
<img width="322" alt="Screenshot 2021-10-03 at 1 11 21 AM" src="https://user-images.githubusercontent.com/72069769/135729850-7f4205b1-d140-4dcc-a32e-736428115f7e.png">

**Comment by pccoder-2000** [comment]
I would like to contribute to this issue.

**Comment by iamHrithikRaj** [comment]
I'd love to be assigned on this one. :)

**Comment by Amritanshu02** [comment]
Hello, I would like to work upon this, could you please assign it to me

**Comment by ahmadsohail404** [comment]
Go ahead!!

**Comment by Madhavman** [comment]
i will do

**Comment by ahmadsohail404** [comment]
make it responsive

**Comment by mukulsinghal407** [comment]
I would like to contribute to this issue as well

**Comment by harshit-dugar** [comment]
@ahmadsohail404 can you please explain me the issue in this

**Comment by ahmadsohail404** [comment]
<img width="340" alt="Screenshot 2021-10-04 at 9 29 21 PM" src="https://user-images.githubusercontent.com/72069769/135884421-85c5c3b4-7c3e-47fe-8309-a96cfcb6a00b.png">

what's the status? @pccoder-2000 @Amritanshu02 @Madhavman

**Comment by Madhavman** [comment]
Ok I have to create a website or

**Comment by Madhavman** [comment]
I can only create a  full website and you can modify accordingly
