### ISSUE TITLE
Add support for regional language (Hindi)

### ISSUE THREAD

**Issue by iamHrithikRaj** [ahmadsohail404/Netflix-UI-Clone#30]
Similar to the <a href="https://www.netflix.com/in/">official website</a> we can add support for Hindi language as well.

**Comment by iamHrithikRaj** [comment]
I would like to work on this. :)

**Comment by ahmadsohail404** [comment]
go ahead

**Comment by nayanbari** [comment]
@ahmadsohail404 I would like to work on this issue. Will you assign this to me if available?

**Comment by ahmadsohail404** [comment]
@iamHrithikRaj What's the status?

**Comment by iamHrithikRaj** [comment]
> @iamHrithikRaj What's the status?

I'll open up a PR in sometime. :)

**Comment by iamHrithikRaj** [comment]
@ahmadsohail404 will this get merged?
