### ISSUE TITLE
Need to add a sign up page

### ISSUE THREAD

**Issue by Amritanshu02** [ahmadsohail404/Netflix-UI-Clone#32]
There is no sign up page for the new users.

**Comment by Amritanshu02** [comment]
Hello, I would like to work upon this issue, please assign it to me.

**Comment by ahmadsohail404** [comment]
go ahead

**Comment by YVishnoi** [comment]
Hello Sir, I wanted to contribute in this project. Please assign this task to me

**Comment by Abhishek07-0302** [comment]
Hey, I would like to contribute. Kindly assign me if available.

**Comment by aathirav06** [comment]
hello, @ahmadsohail404 please assign me this issue. I will make a good looking responsive login and registration page

**Comment by ahmadsohail404** [comment]
go ahead. also in the sign in page fix the spacing of signup bars

**Comment by Amritanshu02** [comment]
I had created the sign up page also resolved the conflict in the PR. I will
upload the screenshot today evening.

**Comment by harshit-dugar** [comment]
Hello @ahmadsohail404 I want to contribute to this issue kindly assign me if available  .

**Comment by Deepakv14** [comment]
@ahmadsohail404 Can I work on it?? Please assign it to me if available

**Comment by ahmadsohail404** [comment]
@Amritanshu02 what's the status??

**Comment by Amritanshu02** [comment]
> @Amritanshu02 what's the status??

Sir I had created a new PR name as "New PR on added sign up" thats working completely fine and has no conflict, you can merge it!

**Comment by aathirav06** [comment]
@ahmadsohail404 I have created the signup page and also added language preference
