### ISSUE TITLE
Correct spelling mistake in FAQ section

### ISSUE THREAD

**Issue by imobasshir** [ahmadsohail404/Netflix-UI-Clone#46]
If it is valid issue assign it to me under hacktober

**Comment by himanshu-malviya15** [comment]
I am created PR please review

**Comment by imobasshir** [comment]
I have created issue first then how can you create pr.

**Comment by ahmadsohail404** [comment]
attach the screenshot of the changes u have made here in the comment section

**Comment by imobasshir** [comment]
Please assign this to me

**Comment by imobasshir** [comment]
### Website link
https://imobasshir.github.io/Netflix-UI-LandingPage/
### Initially
![initiallyFAQ](https://user-images.githubusercontent.com/62945306/135863573-8e6c3b00-1b40-4d6d-a6b0-bd3b7ffed3dd.png)
### Now
![now](https://user-images.githubusercontent.com/62945306/135863679-0a35353e-a8b2-4325-b426-c50c18b5e34a.png)

pr: #59 
I have corrected in linked pr @ahmadsohail404 
Please review it.
