### ISSUE TITLE
Add config file for Prettier

### ISSUE THREAD

**Issue by omeiirr** [ahmadsohail404/Netflix-UI-Clone#56]
Add config file for Prettier to prevent conflicts between tab spaces and single/double quotes

**Comment by ahmadsohail404** [comment]
@omeiirr wanna go ahead wid it?

**Comment by omeiirr** [comment]
Sure
Going by the current structure of this project, I'm thinking
```js
{
  "tabWidth": 2,
  "singleQuote": false,
  "bracketSpacing": true
}
```

What else do you feel is useful?
Here's a [list](https://prettier.io/docs/en/options.html) to help you decide.

**Comment by ahmadsohail404** [comment]
@omeiirr go ahead wid it

**Comment by omeiirr** [comment]
Done
