### ISSUE TITLE
UI is breaking on small screens

### ISSUE THREAD

**Issue by nayyyhaa** [ahmadsohail404/Netflix-UI-Clone#62]
UI is breaking on a small(320 x 568) dimension screen. PFA the SS

**SS:**
1) **In homepage**, X-scroll is overflowing.
![image](https://user-images.githubusercontent.com/46138150/135893078-9b9f42f6-1f53-4cc7-b471-30ebc09a3f47.png)

2) **Sign Up page:** Social media buttons are distorted and sign-up message is not in center.
![image](https://user-images.githubusercontent.com/46138150/135893215-273c4814-6dd5-41eb-b845-8050ac030985.png)

**Comment by ahmadsohail404** [comment]
host it nd put the link here for reveiwing

**Comment by nayyyhaa** [comment]
> host it nd put the link here for reviewing

Link: https://netflix-nayyyhaa.netlify.app/

**Comment by ahmadsohail404** [comment]
done
