### ISSUE TITLE
 Footer CSS can be modified, In original site it looks way better.

### ISSUE THREAD

**Issue by luv2001** [ahmadsohail404/Netflix-UI-Clone#67]
### Footer Css same as original
![Screenshot 2021-10-05 at 12 40 44 AM](https://user-images.githubusercontent.com/59383433/135910443-34c143e1-a2de-4c59-80f2-b6f1edf828a4.png)

**Comment by merikettapearl212** [comment]
Do you still need help with this? thank you

**Comment by ahmadsohail404** [comment]
go ahead!

**Comment by luv2001** [comment]
Sir @ahmadsohail404 , I raised that issue before @merikettapearl212  

Could you please assign it to me **_OR_** both of us.
Thank you
