### ISSUE TITLE
⚠️ Hosted website shows Deceptive Website Warning 

### ISSUE THREAD

**Issue by iamHrithikRaj** [ahmadsohail404/Netflix-UI-Clone#69]
The <a href="https://ahmadsohail404.github.io/Netflix-UI-LandingPage/">hosted site</a> shows(below) that its a Deceptive Website because of being a clone. 
Can the project be excluded from Hacktoberfest because of this reason?

<img width="1440" alt="Screen Shot 2021-10-05 at 4 43 07 AM" src="https://user-images.githubusercontent.com/50907893/135936786-ac3bd4c7-3087-4934-af08-b9d7ad11d83f.png">

**Comment by ahmadsohail404** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/72069769/135992007-fa588604-4a9d-482b-8f00-23f173706eb9.png)

No, It's just a code issue and will be fixed soon.

**Comment by amarjeetsinha** [comment]
Should I host the website?

**Comment by ahmadsohail404** [comment]
@amarjeetsinha make the website free from warning, it's been hosted already

**Comment by ahmadsohail404** [comment]
> Should I host the website?

Do it, let's see
