### ISSUE TITLE
Accordion should open one at a time.

### ISSUE THREAD

**Issue by iamHrithikRaj** [ahmadsohail404/Netflix-UI-Clone#7]
On the official <a href="https://www.netflix.com/in/">Netflix website</a> the accordion opens one FAQ at a time i.e., if other FAQ is opened the previous one closes automatically.

**Comment by iamHrithikRaj** [comment]
I'd love to be assigned on this one. :)

**Comment by ahmadsohail404** [comment]
Go ahead!
