### ISSUE TITLE
Fix the deceptive website warning !

### ISSUE THREAD

**Issue by ahmadsohail404** [ahmadsohail404/Netflix-UI-Clone#85]
<img width="1440" alt="Screenshot 2021-10-17 at 11 20 57 PM" src="https://user-images.githubusercontent.com/72069769/137638956-6392af47-6c81-4ead-b804-dbf6d53c3b98.png">

**Comment by harshit-dugar** [comment]
I am ready to work on it 
Please assign me @ahmadsohail404

**Comment by ahmadsohail404** [comment]
Go ahead @harshit-dugar

**Comment by ahmadsohail404** [comment]
@harshit-dugar What's the status?

**Comment by harshit-dugar** [comment]
> @harshit-dugar What's the status?

Working on it
